blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.post_list, name='index'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from mysite.views import HomeView, UserRegisterView, UserRegisterDoneView, validate_username

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^accounts/register/$', UserRegisterView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserRegisterDoneView.as_view(), name='register_done'),
    url(r'^ajax/validate_username/$', validate_username, name="validate_username"),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^books/', include('books.urls', namespace="books")),
    url(r'^board/', include('board.urls', namespace="board")),
]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length = 200)
    text = models.TextField()
    created_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank = True, null = True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()
    
    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from .urls import *

# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
        return render(request, 'blog/post_edit.html', {'form':form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
        return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog.views.post_list')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)

blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>수업내용기록</title>
    <link rel="stylesheet" href="index.css">
</head>

<body>
    <div style="position:relative; border:2px dashed red; width:200px; height:100px; background-color: pink;text-align: center;">
        <div style="position: absolute; top:50%; left:50%; transform:translate(-50%,-50%); padding:10px; width:100%;">
            <span style="color:red;font-weight:bold;">※ WARNING ※<br>체력이 부족합니다.</span><br>
            <meter value="20" min="0" max="100" style="margin-top:10px;"></meter>
        </div>
    </div>
    <h1>중요 작업 리스트</h1>
    <ul>
        <li><a href="/">수업자료</a></li>
        <li><a href="member/index.html">비상연락망</a></li>
        <li><a href="index_grid.html">4x4 표같은 버튼 목록 만들기</a></li>
        <li><a href="social/index.html">여성인력 완성 작업</a></li>
        <li><a href="MyPage/index.html">개인 페이지 만들기</a></li>
        <li><a href="savedata.php">데이터 수집용 PHP</a></li>
        <li><a href="psd-to-codding/index.html">포토샵 예제 코딩하기</a></li>
        <li><a href="/~c19jjk/team-mango/">팀 프로젝트 #1</a></li>
        <li><a href="JS/1113/firstCal.html">자작 계산기(출시판?)</a></li>
    </ul>
    <h1>2017년 8월</h1>
    <h3 style="color:red">※ 하위폴더 정리작업중</h3>
    <h3 style="color:red">※ 각 날짜 수업 내용 요약할 것</h3>
    <ul class="squarelist august">
        <li><a href="08/0801/index.html">8월 1일<br>(입문)</a></li>
        <li><a href="08/0802/index.html">8월 2일<br>(제목)</a></li>
        <li><a href="08/0803/index.html">8월 3일<br>(태그)</a></li>
        <li><a href="08/0804/index.html">8월 4일<br>(예제-포스터)</a></li>
        <li><a href="08/0807/index.html">8월 7일<br>(외부 CSS)</a></li>
        <li><a href="08/0808/myhome.html">8월 8일<br>(예제-글자상점)</a></li>
        <li><a href="08/0809/0809_3.html">8월 9일<br>(새창열기, 클래스,<br>이미지맵)</a></li>
        <li><a href="08/0810/index.html">8월 10일<br>(테이블)</a></li>
        <li><a href="08/0811/index.html">8월 11일<br>(장식버튼)</a></li>
        <li><a href="08/0816/index.html">8월 16일<br>(페이지 구성)</a></li>
        <li><a href="08/0817/index.html">8월 17일<br>(1차 사이트 제작)</a></li>
        <li>
            <del>8월 22일<br>(예비군)</del>
        </li>
        <li><a href="08/0823/index.html">8월 23일<br>(포지션&플로트)</a></li>
        <li><a href="08/0824/index.html">8월 24일<br>(사이트 만들기)</a></li>
        <li><a href="08/0828/index.html">8월 28일<br>(플로트 박스)</a></li>
        <li><a href="08/0830/index.html">8월 30일<br>(내비게이션 바)</a></li>
    </ul>
    <h1>2017년 9월</h1>
    <ul class="squarelist september">
        <li><a href="0901/index.html">9월 1일<br>(사이트 만들기-<br>동물원)</a></li>
        <li><a href="0905/index.html">9월 5일<br>(카운터 등등)</a></li>
        <li><a href="0906/index.html">9월 6일<br>(겟vs포스트,<br>폼 디자인 등등)</a></li>
        <li><a href="0907/index.html">9월 7일<br>(PHP 등)</a></li>
        <li><a href="0912/index.html">9월 12일<br>(구글 지도 사용)</a></li>
        <li><a href="0913/index.html">9월 13일<br>(CSS 캔버스)</a></li>
        <li><a href="0914/index.html">9월 14일<br>(웹폰트 사용)</a></li>
        <li><a href="0918/index.html">9월 18일<br>(플렉스박스 입문)</a></li>
        <li><a href="0921/index.html">9월 21일<br>(반응형 웹 입문)</a></li>
        <li><a href="/~c19jjk/team-mango/">9월 25일 ~ 29일<br>(조별과제 #1)</a></li>
    </ul>
    <h1>2017년 10월</h1>
    <ul class="squarelist october">
        <li><a href="JS/1010/index.html">10월 10일<br>(자바스크립트,<br>숫자맞추기)</a></li>
        <li><a href="JS/1011/index.html">10월 11일<br>(교재 예시)</a></li>
        <li><a href="JS/1012/index.html">10월 12일<br>(if ... else)</a></li>
        <li><a href="JS/1013/index.html">10월 13일<br>(여러 가지 예시)</a></li>
        <li><a href="JS/1016/index.html">10월 16일<br>(로컬/글로벌)</a></li>
        <li><a href="JS/1017/index.html">10월 17일<br>(실전: 입사년도<br>계산)</a></li>
        <li><a href="JS/1018/index.html">10월 18일<br>(앞에서 계속)</a></li>
        <li><a href="JS/1020/index.html">10월 20일<br>(작업 중단)</a></li>
        <li><a href="JS/1023/index.html">10월 23일<br>(랜덤 & 추첨)</a></li>
        <li><a href="JS/1025/index.html">10월 25일<br>(창작 연습 #1)</a></li>
        <li><a href="JS/1026/index.html">10월 26일<br>(창작 연습 #2)</a></li>
        <li><a href="JS/1027/index.html">10월 27일<br>(시계 만들기<br>(독학?))</a></li>
        <li><a href="JS/1030/index.html">10월 30일<br>(불 속성 연습)</a></li>
        <li><a href="JS/1031/index.html">10월 31일<br>(객체 만들기 연습<br>(보교재))</a></li>
    </ul>
    <h1>2017년 11월</h1>
    <ul class="squarelist november">
        <li><a href="JS/1101/index.html">11월 1일<br>(계산기 이해)</a></li>
        <li><a href="JS/1102/index.html">11월 2일<br>(계산기 만들기&설명)</a></li>
        <li><a href="JS/1103/index.html">11월 3일<br>(간단 예제)</a></li>
        <li><a href="JS/1106/index.html">11월 6일<br>(생성자 함수)</a></li>
        <li><a href="JS/1107/index.html">11월 7일<br>(유효성 검사)</a></li>
        <li><a href="JS/1108/index.html">11월 8일<br>(남의 계산기 참고)</a></li>
        <li><a href="JS/1109/index.html">11월 9일<br>(함수 연습)</a></li>
        <li><a href="JS/1113/index.html">11월 13일<br>(자작 계산기)</a></li>
        <li><a href="JS/1115/index.html">11월 15일<br>(띄어쓰기 찾기)</a></li>
        <li><a href="JS/1120/index.html">11월 20일<br>(AJAX 기초)</a></li>
        <li><a href="JS/1121/index.html">11월 21일<br>(AJAX와 DB)</a></li>
    </ul>
</body>

</html>

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>새 댓글</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">전송</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}
<html>
<head>
    <title>Django Girls blog</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>

    <div class="page-header">
        {% if user.is_authenticated %}
        <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
        <p class="top-menu">환영합니다, '{{ user.username }}'님! <small>(<a href="{% url 'logout' %}">로그아웃</a>)</small></p>
        {% else %}
        <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
        {% endif %}
        <h1><a href="/">Django Girls Blog</a></h1>
    </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p>일단은 blog의 index입니다. 지금은 홈페이지가 아닙니다.<br>
    실제 홈페이지는 base.html이기 때문입니다.</p>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
        <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">배포</a>
        {% endif %}
        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
    <hr>
    <a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">댓글 쓰기</a>
    {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
        <div class="comment">
            <div class="date">
                {{ comment.created_date }}
                {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                {% endif %}
            </div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
        {% endif %}
    {% empty %}
        <p>현재 코멘트가 없습니다. (-_-)</p>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y'}}</p>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">완료</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                <p>published: {{ post.published_date }}</p>
            </div>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
            <a href="{% url 'blog:post_detail' pk=post.pk %}">댓글: {{ post.approved_comments.count }}개</a>
        </div>
    {% endfor %}
{% endblock %}