blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.post_list, name='index'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from mysite.views import HomeView, UserRegisterView, UserRegisterDoneView, validate_username

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^accounts/register/$', UserRegisterView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserRegisterDoneView.as_view(), name='register_done'),
    url(r'^ajax/validate_username/$', validate_username, name="validate_username"),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^books/', include('books.urls', namespace="books")),
    url(r'^board/', include('board.urls', namespace="board")),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% block base_style %}{% static 'css/base.css' %}{% endblock %}">
    <link rel="stylesheet" type="text/css" href="{% block extra_style %}{% endblock %}" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title %}장고 게시판{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="/" class="navbar-brand">DJANGO PROJECT v12.07</a>
            </div>
        </div>
        <ul class="nav navbar-nav">
            <li>
                <a href="{% url 'home' %}">
                    <span class="glyphicon glyphicon-home"></span></a>
            </li>
            <li>
                <a href="{% url 'board:index' %}">
                    <span class="glyphicon glyphicon-list-alt"></span>게시판</a>
            </li>
            <li>
                <a href="{% url 'books:index' %}">책들</a>
            </li>
            <li>
                <a href="{% url 'polls:index' %}">투표</a>
            </li>
            <li>
                <a href="{% url 'blog:index' %}">블로그</a>
            </li>
            {% if user.is_superuser %}
            <li>
                <a href="{% url 'admin:index' %}">
                    <i class="fa fa-cog fa-spin"></i>페이지 관리</a>
            </li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav" style="float:right;">
            {% if user.is_active %}
            <li>
                <a href="{% url 'password_change' %}">비밀번호 변경</a>
            </li>
            <li>
                <a href="{% url 'logout' %}">로그아웃</a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'login' %}">로그인</a>
            </li>
            <li>
                <a href="{% url 'register' %}">회원가입</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% if user.is_active %}
    <div class="container alert alert-success">
            <p>{% firstof user.get_short_name user.get_username %}님, 환영합니다.</p>
    </div>
    {% endif %}
    {% if user.is_superuser %}
    <div class="container alert alert-warning">
            <p>관리자 계정으로 로그인하셨습니다. 페이지 관리에 주의해 주십시오.</p>
    </div>
    {% endif %}
    <div class="container alert alert-info">
        <p>관리자께서는 로그인하여 주십시오.</p>
    </div>

    <div>
        <h1>{% block subtitle %}{% endblock %}</h1>
    </div>
    <div>
        {% block content %}{% endblock %}
    </div>
    {% block footer %}
    <div>&copy; 2017. Django & LHGⓒ All Rights Reserved.</div>
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
    {% block javascript %}{% endblock %}
</body>

</html>

templates/base_books.html
{% extends "base.html" %}

<title>{% block title %}Book Application Site{% endblock %}</title>

{% block sidebar %}
{{ block.super }}
<ul>
    <li><a href="/books/">Books_Home</a></li>
</ul>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% load staticfiles %}

{% block content %}
<div class="jumbotron">
    <h2>메인 페이지입니다.</h2>
    <p>말 잘하는 사람이 홈페이지 소개문구 작성할 예정</p>
</div>
{% endblock content %}